// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/finalProject.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExprRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val1          float32                `protobuf:"fixed32,1,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2          float32                `protobuf:"fixed32,2,opt,name=val2,proto3" json:"val2,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExprRequest) Reset() {
	*x = ExprRequest{}
	mi := &file_proto_finalProject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExprRequest) ProtoMessage() {}

func (x *ExprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExprRequest.ProtoReflect.Descriptor instead.
func (*ExprRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{0}
}

func (x *ExprRequest) GetVal1() float32 {
	if x != nil {
		return x.Val1
	}
	return 0
}

func (x *ExprRequest) GetVal2() float32 {
	if x != nil {
		return x.Val2
	}
	return 0
}

func (x *ExprRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_finalProject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubResponse) Reset() {
	*x = SubResponse{}
	mi := &file_proto_finalProject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse) ProtoMessage() {}

func (x *SubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse.ProtoReflect.Descriptor instead.
func (*SubResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{2}
}

func (x *SubResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MulResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MulResponse) Reset() {
	*x = MulResponse{}
	mi := &file_proto_finalProject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulResponse) ProtoMessage() {}

func (x *MulResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulResponse.ProtoReflect.Descriptor instead.
func (*MulResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{3}
}

func (x *MulResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type DiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_proto_finalProject_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{4}
}

func (x *DiffResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_finalProject_proto protoreflect.FileDescriptor

const file_proto_finalProject_proto_rawDesc = "" +
	"\n" +
	"\x18proto/finalProject.proto\x12\ffinalProject\"E\n" +
	"\vExprRequest\x12\x12\n" +
	"\x04val1\x18\x01 \x01(\x02R\x04val1\x12\x12\n" +
	"\x04val2\x18\x02 \x01(\x02R\x04val2\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\"%\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"%\n" +
	"\vSubResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"%\n" +
	"\vMulResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"&\n" +
	"\fDiffResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result2\x83\x02\n" +
	"\vCalcService\x12;\n" +
	"\x03Add\x12\x19.finalProject.ExprRequest\x1a\x19.finalProject.AddResponse\x12;\n" +
	"\x03Sub\x12\x19.finalProject.ExprRequest\x1a\x19.finalProject.SubResponse\x12;\n" +
	"\x03Mul\x12\x19.finalProject.ExprRequest\x1a\x19.finalProject.MulResponse\x12=\n" +
	"\x04Diff\x12\x19.finalProject.ExprRequest\x1a\x1a.finalProject.DiffResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_finalProject_proto_rawDescOnce sync.Once
	file_proto_finalProject_proto_rawDescData []byte
)

func file_proto_finalProject_proto_rawDescGZIP() []byte {
	file_proto_finalProject_proto_rawDescOnce.Do(func() {
		file_proto_finalProject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finalProject_proto_rawDesc), len(file_proto_finalProject_proto_rawDesc)))
	})
	return file_proto_finalProject_proto_rawDescData
}

var file_proto_finalProject_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_finalProject_proto_goTypes = []any{
	(*ExprRequest)(nil),  // 0: finalProject.ExprRequest
	(*AddResponse)(nil),  // 1: finalProject.AddResponse
	(*SubResponse)(nil),  // 2: finalProject.SubResponse
	(*MulResponse)(nil),  // 3: finalProject.MulResponse
	(*DiffResponse)(nil), // 4: finalProject.DiffResponse
}
var file_proto_finalProject_proto_depIdxs = []int32{
	0, // 0: finalProject.CalcService.Add:input_type -> finalProject.ExprRequest
	0, // 1: finalProject.CalcService.Sub:input_type -> finalProject.ExprRequest
	0, // 2: finalProject.CalcService.Mul:input_type -> finalProject.ExprRequest
	0, // 3: finalProject.CalcService.Diff:input_type -> finalProject.ExprRequest
	1, // 4: finalProject.CalcService.Add:output_type -> finalProject.AddResponse
	2, // 5: finalProject.CalcService.Sub:output_type -> finalProject.SubResponse
	3, // 6: finalProject.CalcService.Mul:output_type -> finalProject.MulResponse
	4, // 7: finalProject.CalcService.Diff:output_type -> finalProject.DiffResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_finalProject_proto_init() }
func file_proto_finalProject_proto_init() {
	if File_proto_finalProject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finalProject_proto_rawDesc), len(file_proto_finalProject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finalProject_proto_goTypes,
		DependencyIndexes: file_proto_finalProject_proto_depIdxs,
		MessageInfos:      file_proto_finalProject_proto_msgTypes,
	}.Build()
	File_proto_finalProject_proto = out.File
	file_proto_finalProject_proto_goTypes = nil
	file_proto_finalProject_proto_depIdxs = nil
}
