// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/finalProject.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Result        float32                `protobuf:"fixed32,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error         bool                   `protobuf:"varint,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskRequest) Reset() {
	*x = SetTaskRequest{}
	mi := &file_proto_finalProject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskRequest) ProtoMessage() {}

func (x *SetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskRequest.ProtoReflect.Descriptor instead.
func (*SetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{0}
}

func (x *SetTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetTaskRequest) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SetTaskRequest) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type SetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTaskResponse) Reset() {
	*x = SetTaskResponse{}
	mi := &file_proto_finalProject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTaskResponse) ProtoMessage() {}

func (x *SetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTaskResponse.ProtoReflect.Descriptor instead.
func (*SetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{1}
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_finalProject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{2}
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Arg1          float32                `protobuf:"fixed32,2,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2          float32                `protobuf:"fixed32,3,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
	OperationTime int32                  `protobuf:"varint,5,opt,name=Operation_time,json=OperationTime,proto3" json:"Operation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_finalProject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finalProject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_finalProject_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskResponse) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *GetTaskResponse) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *GetTaskResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *GetTaskResponse) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

var File_proto_finalProject_proto protoreflect.FileDescriptor

const file_proto_finalProject_proto_rawDesc = "" +
	"\n" +
	"\x18proto/finalProject.proto\x12\ffinalProject\"N\n" +
	"\x0eSetTaskRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Result\x18\x02 \x01(\x02R\x06Result\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\bR\x05Error\"\x11\n" +
	"\x0fSetTaskResponse\"\x10\n" +
	"\x0eGetTaskRequest\"\x8e\x01\n" +
	"\x0fGetTaskResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Arg1\x18\x02 \x01(\x02R\x04Arg1\x12\x12\n" +
	"\x04Arg2\x18\x03 \x01(\x02R\x04Arg2\x12\x1c\n" +
	"\tOperation\x18\x04 \x01(\tR\tOperation\x12%\n" +
	"\x0eOperation_time\x18\x05 \x01(\x05R\rOperationTime2\x9d\x01\n" +
	"\vCalcService\x12F\n" +
	"\aGetTask\x12\x1c.finalProject.GetTaskRequest\x1a\x1d.finalProject.GetTaskResponse\x12F\n" +
	"\aSetTask\x12\x1c.finalProject.SetTaskRequest\x1a\x1d.finalProject.SetTaskResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_finalProject_proto_rawDescOnce sync.Once
	file_proto_finalProject_proto_rawDescData []byte
)

func file_proto_finalProject_proto_rawDescGZIP() []byte {
	file_proto_finalProject_proto_rawDescOnce.Do(func() {
		file_proto_finalProject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finalProject_proto_rawDesc), len(file_proto_finalProject_proto_rawDesc)))
	})
	return file_proto_finalProject_proto_rawDescData
}

var file_proto_finalProject_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_finalProject_proto_goTypes = []any{
	(*SetTaskRequest)(nil),  // 0: finalProject.SetTaskRequest
	(*SetTaskResponse)(nil), // 1: finalProject.SetTaskResponse
	(*GetTaskRequest)(nil),  // 2: finalProject.GetTaskRequest
	(*GetTaskResponse)(nil), // 3: finalProject.GetTaskResponse
}
var file_proto_finalProject_proto_depIdxs = []int32{
	2, // 0: finalProject.CalcService.GetTask:input_type -> finalProject.GetTaskRequest
	0, // 1: finalProject.CalcService.SetTask:input_type -> finalProject.SetTaskRequest
	3, // 2: finalProject.CalcService.GetTask:output_type -> finalProject.GetTaskResponse
	1, // 3: finalProject.CalcService.SetTask:output_type -> finalProject.SetTaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_finalProject_proto_init() }
func file_proto_finalProject_proto_init() {
	if File_proto_finalProject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finalProject_proto_rawDesc), len(file_proto_finalProject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finalProject_proto_goTypes,
		DependencyIndexes: file_proto_finalProject_proto_depIdxs,
		MessageInfos:      file_proto_finalProject_proto_msgTypes,
	}.Build()
	File_proto_finalProject_proto = out.File
	file_proto_finalProject_proto_goTypes = nil
	file_proto_finalProject_proto_depIdxs = nil
}
